/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as PrivateImport } from './routes/_private'
import { Route as IndexImport } from './routes/index'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard/route'
import { Route as PrivateDashboardIndexImport } from './routes/_private/dashboard/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PrivateDashboardRouteRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateDashboardIndexRoute = PrivateDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateDashboardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateImport
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof PrivateDashboardIndexImport
      parentRoute: typeof PrivateDashboardRouteImport
    }
  }
}

// Create and export the route tree

interface PrivateDashboardRouteRouteChildren {
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
}

const PrivateDashboardRouteRouteChildren: PrivateDashboardRouteRouteChildren = {
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
}

const PrivateDashboardRouteRouteWithChildren =
  PrivateDashboardRouteRoute._addFileChildren(
    PrivateDashboardRouteRouteChildren,
  )

interface PrivateRouteChildren {
  PrivateDashboardRouteRoute: typeof PrivateDashboardRouteRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRouteRoute: PrivateDashboardRouteRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof PrivateDashboardRouteRouteWithChildren
  '/dashboard/': typeof PrivateDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/_private/dashboard': typeof PrivateDashboardRouteRouteWithChildren
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/dashboard' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/login'
    | '/_private/dashboard'
    | '/_private/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_private",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/dashboard"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_private/dashboard": {
      "filePath": "_private/dashboard/route.tsx",
      "parent": "/_private",
      "children": [
        "/_private/dashboard/"
      ]
    },
    "/_private/dashboard/": {
      "filePath": "_private/dashboard/index.tsx",
      "parent": "/_private/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
